name: Atualizar BLUE

on:
  workflow_dispatch:
    inputs:
      jsonContent:
        description: "Conteúdo do JSON em Base64"
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Decodificar e salvar JSON
      run: |
        echo "Validando o input recebido em Base64..."
        echo "${{ github.event.inputs.jsonContent }}"

        echo "Decodificando o conteúdo Base64..."
        printf '%s' "$(echo '${{ github.event.inputs.jsonContent }}' | base64 --decode)" > green.json

        echo "Conteúdo decodificado salvo em blue.json:"
        cat green.json

    - name: Configurar Git para autenticação
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Garantir que o repositório está atualizado
      run: |
        git fetch --all
        git pull origin main || echo "Nada para atualizar"

    - name: Commit e Push
      run: |
        git add green.json
        git diff --cached --quiet || git commit -m "Atualização do arquivo JSON via GitHub Actions"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
