name: Atualizar JSON

on:
  workflow_dispatch:
    inputs:
      jsonContent:
        description: "Conteúdo do JSON em Base64"
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Decodificar e salvar JSON
      run: |
        echo "Validando o input recebido em Base64..."
        echo "${{ github.event.inputs.jsonContent }}"

        echo "Decodificando o conteúdo Base64..."
        printf '%s' "$(echo '${{ github.event.inputs.jsonContent }}' | base64 --decode)" > blue.json

        echo "Conteúdo decodificado salvo em blue.json:"
        cat blue.json

    - name: Commit e Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add blue.json
        git commit -m "Atualização do arquivo JSON via GitHub Actions"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
