name: Atualizar JSON

on:
  workflow_dispatch:
    inputs:
      jsonContent:
        description: "Novo conteúdo JSON (em base64)"
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      # Passo 2: Decodificar o conteúdo JSON e salvar no arquivo
      - name: Atualizar JSON
        run: |
          echo "${{ github.event.inputs.jsonContent }}" | base64 --decode > blue.json

      # Passo 3: Commitar e enviar as alterações para o repositório
      - name: Commit e Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add blue.json
          git commit -m "Atualização do arquivo JSON via GitHub Actions"
          git push
